name: DeployVNET

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: azlogin
      uses: ./.github/actions/azlogin
      with:
        identity: 'True'
        environmentName: 'AzureCloud' 
#        clientId: ${{ secrets.AZURE_CRED.clientId }}
#        clientSecret: ${{ secrets.AZURE_CRED.clientSecret }}
#        tenantId: ${{ secrets.AZURE_CRED.tenantId }}
#        subscriptionId: ${{ secrets.AZURE_CRED.subscriptionId }}
    
#================================================================
# =================== DEV Network Security Groups ===============
# ===============================================================

    - name: 'Network Security Group: VNET-West-DEV-NSG'
      uses: ./.github/actions/azdeploy
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/NetworkSecurityGroups/2019-11-28/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/NetworkSecurityGroups/VNET-West-DEV-NSG.json'
        resourceGroupCommand: 'create'

  # ===============================================================
  # ======================== DEV Route Tables =====================
  # ===============================================================

    - name: 'Route Table: VNET-West-DEV-udr'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/RouteTables/2020-03-03/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/RouteTables/VNET-West-DEV-udr.json'  

# ===============================================================    
# ======================= DEV Virtual Network ===================
# ===============================================================
        
    - name: 'Virtual Network: VNET-West-DEV'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualNetwork/2020-03-09/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/VirtualNetwork/VNET-West-DEV.json'

#================================================================
# =================== PROD Network Security Groups ==============
# ===============================================================

    - name: 'Network Security Group: VNET-West-PROD-NSG'
      uses: ./.github/actions/azdeploy
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/NetworkSecurityGroups/2019-11-28/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Prod/NetworkSecurityGroups/VNET-West-PROD-NSG.json'
        resourceGroupCommand: 'create'

  # ===============================================================
  # ======================== PROD Route Tables ====================
  # ===============================================================

    - name: 'Route Table: VNET-West-PROD-udr'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/RouteTables/2020-03-03/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Prod/RouteTables/VNET-West-PROD-udr.json'  

# ===============================================================    
# ======================= PROD Virtual Network ==================
# ===============================================================
        
    - name: 'Virtual Network: VNET-West-PROD'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualNetwork/2020-03-09/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Prod/VirtualNetwork/VNET-West-PROD.json'

