name: DeployVNET

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  resourceGroupName: 'Dev-West'
  location: 'westus2'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CRED}}

          # This is for Dev VNET Deployment

      - name: Deploy Azure VNET Dev West
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'VNET', 'subscription'
          scope: 'subscription'
          # Override the Subscription Id set by Azure Login.
          subscriptionId: '8dea3428-7d28-49bf-9340-2aafb548a0d2'
          # Specify the path or URL to the Azure Resource Manager template.
          template: 'Modules/ARM/VirtualNetwork/deploy.json'
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: 'Incremental'
          # Specifies the name of the resource group deployment to create.
          deploymentName: 'Deploy-Azure-VNET'
          # Supply deployment parameter values.
          parameters: 'Team5Litware/Parameters/West/Dev/VNET-West-DEV.json'

#================================================================
# =================== Network Security Groups =================== 
# ===============================================================

    - name: 'Network Security Group: VNET-West-DEV-NSG'
      uses: ./.github/actions/azdeploy
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/NetworkSecurityGroups/2019-11-28/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/NetworkSecurityGroups/VNET-West-DEV-NSG.json'
        resourceGroupCommand: 'create'

  # ===============================================================
  # ======================== Route Tables =========================
  # ===============================================================

    - name: 'Route Table: VNET-West-DEV-udr'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/RouteTables/2020-03-03/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/RouteTables/VNET-West-DEV-udr.json'  

# ===============================================================    
# ======================= Virtual Network =======================
# ===============================================================
        
    - name: 'Virtual Network: VNET-West-DEV'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualNetwork/2020-03-09/deploy.json'
        parametersFile: 'Team5Litware/Parameters/West/Dev/VirtualNetwork/VNET-West-DEV.json'